package com.zacknetic.zoomintegration.zoom.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request model for creating or updating Zoom meetings.
 *
 * Fellow Standards: Production-ready request builder pattern
 * Security: No sensitive data stored, passwords generated by Zoom if needed
 * Explicit: Clear field names matching Zoom API expectations
 *
 * Zoom API Reference: https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingCreate
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL) // Only include non-null fields in JSON
public class ZoomMeetingRequest {

    /**
     * Meeting topic (required)
     * Max length: 200 characters
     */
    @JsonProperty("topic")
    private String topic;

    /**
     * Meeting type
     * 1=Instant, 2=Scheduled (default), 3=Recurring (no fixed time), 8=Recurring (fixed time)
     */
    @JsonProperty("type")
    @Builder.Default
    private Integer type = 2; // Scheduled meeting by default

    /**
     * Meeting start time in ISO 8601 format
     * Required for scheduled meetings (type=2 or 8)
     * Example: "2024-01-15T14:00:00Z" or "2024-01-15T14:00:00"
     */
    @JsonProperty("start_time")
    private String startTime;

    /**
     * Meeting duration in minutes
     * Default: 60 minutes
     */
    @JsonProperty("duration")
    @Builder.Default
    private Integer duration = 60;

    /**
     * Timezone for start_time
     * Example: "America/Los_Angeles", "UTC"
     * If not provided, uses account's default timezone
     */
    @JsonProperty("timezone")
    private String timezone;

    /**
     * Meeting password
     * Security: Must meet Zoom password requirements (if PMI disabled)
     * Leave null to auto-generate
     */
    @JsonProperty("password")
    private String password;

    /**
     * Meeting agenda/description
     * Max length: 2000 characters
     */
    @JsonProperty("agenda")
    private String agenda;

    /**
     * Recurrence configuration (for recurring meetings)
     * Production: Complex object for recurring meeting rules
     */
    @JsonProperty("recurrence")
    private Object recurrence;

    /**
     * Meeting settings
     */
    @JsonProperty("settings")
    private ZoomMeetingSettings settings;

    /**
     * Tracking fields for analytics and reporting
     * Production: Array of {field, value} objects
     */
    @JsonProperty("tracking_fields")
    private Object trackingFields;

    /**
     * Template ID to use for this meeting
     * Applies pre-configured settings
     */
    @JsonProperty("template_id")
    private String templateId;

    /**
     * Factory method for quick scheduled meeting creation.
     * Production: Sensible defaults for common use case
     *
     * @param topic Meeting topic/title
     * @param startTime Start time in ISO 8601 format
     * @param durationMinutes Duration in minutes
     * @return Configured meeting request
     */
    public static ZoomMeetingRequest createScheduledMeeting(
        String topic,
        String startTime,
        Integer durationMinutes
    ) {
        return ZoomMeetingRequest.builder()
            .topic(topic)
            .type(2) // Scheduled
            .startTime(startTime)
            .duration(durationMinutes != null ? durationMinutes : 60)
            .settings(ZoomMeetingSettings.builder()
                .waitingRoom(true)
                .hostVideo(true)
                .participantVideo(true)
                .muteUponEntry(false)
                .joinBeforeHost(false)
                .build())
            .build();
    }

    /**
     * Factory method for instant meeting creation.
     * Production: Instant meetings start immediately
     *
     * @param topic Meeting topic/title
     * @return Configured instant meeting request
     */
    public static ZoomMeetingRequest createInstantMeeting(String topic) {
        return ZoomMeetingRequest.builder()
            .topic(topic)
            .type(1) // Instant
            .settings(ZoomMeetingSettings.builder()
                .waitingRoom(false) // Instant meetings typically skip waiting room
                .hostVideo(true)
                .participantVideo(true)
                .build())
            .build();
    }
}
